name: Deploy code to Cloud Composer DAGs bucket

on:
  push:
    branches:
      - test-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Sync repo to Composer DAGs folder
        run: |
          gsutil -m rsync -r -d . gs://${{ secrets.COMPOSER_BUCKET }}/dags
