name: Deploy code to Cloud Composer DAGs bucket

on:
  push:
    branches:
      - feature/add_cdc_pipeline #testagain
      - feature/curated_rules_silver #testcurated1
      - feature/test-dbt-composer
      - feature/gen-master
      - feature/integrate-dag-flows 
      - test-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Sync DAG files
        run: |
          gsutil -m rsync -r -d dags gs://${{ secrets.COMPOSER_BUCKET }}/dags

      - name: Sync pipelines
        run: |
          gsutil -m rsync -r -d pipelines gs://${{ secrets.COMPOSER_BUCKET }}/dags/pipelines

      - name: Sync contracts
        run: |
          gsutil -m rsync -r -d contract gs://${{ secrets.COMPOSER_BUCKET }}/dags/contract

      - name: Sync dbt
        run: |
          gsutil -m rsync -r -d dbt gs://${{ secrets.COMPOSER_BUCKET }}/dags/dbt
